# Generated by Django 4.1.3 on 2022-11-21 21:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='enter customer name ...', max_length=255)),
                ('customer_email', models.CharField(blank=True, help_text='enter customer email ...', max_length=255, null=True)),
                ('customer_phone', models.CharField(help_text='enter customer phone..', max_length=255)),
                ('car_name', models.CharField(help_text='Eg Toyota Land Cruiser ...', max_length=255)),
                ('plate_no', models.CharField(blank=True, help_text='Eg  D200 TZ ...', max_length=255, null=True)),
                ('model_no', models.CharField(blank=True, help_text='car model ...', max_length=255, null=True)),
                ('problem_statement', ckeditor_uploader.fields.RichTextUploadingField(help_text=' bio... ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Customers ',
            },
        ),
    ]
