# Generated by Django 4.1.3 on 2022-11-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plate_no',
            field=models.CharField(help_text='Eg  D200 TZ ...', max_length=255),
        ),
    ]
