# Generated by Django 4.1.3 on 2022-11-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_customer_plate_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='model_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plate_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='problem_statement',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(blank=True, default='', help_text='customer address...', max_length=255, null=True),
        ),
    ]
