# Generated by Django 4.1.3 on 2022-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0003_remove_customer_car_name_remove_customer_model_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="drive_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Drive Name...",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_address",
            field=models.CharField(
                blank=True, help_text="customer address...", max_length=255, null=True
            ),
        ),
    ]
