# Generated by Django 4.1.3 on 2022-12-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_customer_drive_name_alter_customer_customer_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="drive_name",
            new_name="driver_name",
        ),
    ]
