# Generated by Django 4.1.3 on 2022-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0005_rename_drive_name_customer_driver_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="driver_phone",
            field=models.CharField(
                default="", help_text="enter phone..", max_length=255
            ),
        ),
    ]
