# Generated by Django 4.1.3 on 2023-01-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0006_customer_driver_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text=" name ...", max_length=255)),
                ("make", models.CharField(help_text="make  ...", max_length=255)),
                (
                    "requisition_from",
                    models.CharField(help_text="from  ...", max_length=255),
                ),
                (
                    "requisition_to",
                    models.CharField(help_text="to  ...", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorized_by",
                        to="workshop.customer",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued",
                        to="workshop.customer",
                    ),
                ),
                (
                    "request_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_by",
                        to="workshop.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Requisitions ",
            },
        ),
        migrations.CreateModel(
            name="RequisitionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Eg: PC, UNIT...",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "remarks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=65),
                ),
                (
                    "hq_feedback",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisition",
                        to="workshop.requisition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Requisition Details",
            },
        ),
    ]
