# Generated by Django 4.1.3 on 2023-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0008_alter_requisition_authorized_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisitiondetails",
            name="supplier",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
