# Generated by Django 4.1.3 on 2023-02-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_requisitiondetails_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg : MECHANICAL', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AlterField(
            model_name='requisitiondetails',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
