# Generated by Django 4.1.3 on 2022-11-21 21:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('about_service', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text=' about the service ... ', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Eg 0755..', max_length=255)),
                ('region', models.CharField(help_text='Eg Dar Es Salaam]', max_length=255)),
                ('address', models.CharField(help_text='Your address info...', max_length=255)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text=' bio... ', null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('photo', models.ImageField(default='avatar.png', upload_to='profiles')),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('currence_type', models.CharField(choices=[('TZS', 'TZS'), ('USD', 'USD')], default='TZS', help_text='currence type ...', max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=30)),
                ('work_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='Pending', max_length=30)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerorder', to='workshop.customer')),
            ],
            options={
                'verbose_name_plural': 'Customer Requests',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='backoffice.customerorders')),
            ],
            options={
                'verbose_name_plural': 'Solution Details',
            },
        ),
    ]
