# Generated by Django 4.1.3 on 2022-11-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorderdetail',
            options={'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='customerorders',
            options={'verbose_name_plural': 'Customer Order'},
        ),
        migrations.RenameField(
            model_name='customerorders',
            old_name='request_date',
            new_name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='customerorderdetail',
            name='contractor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorderdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customerorderdetail',
            name='unit',
            field=models.CharField(blank=True, help_text='Eg: PC, UNIt...', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorderdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
    ]
