# Generated by Django 4.1.3 on 2022-11-23 09:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_alter_customerorderdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='car_name',
            field=models.CharField(default=2, help_text='Eg Toyota Land Cruiser ...', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorders',
            name='model_no',
            field=models.CharField(blank=True, help_text='car model ...', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='plate_no',
            field=models.CharField(default='', help_text='Eg  D200 TZ ...', max_length=255),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='problem_statement',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', help_text=' bio... '),
        ),
    ]
