# Generated by Django 4.1.3 on 2022-11-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_customerorders_car_name_customerorders_model_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='car_name',
            field=models.CharField(default='', help_text='Eg Toyota Land Cruiser ...', max_length=255),
        ),
    ]
