# Generated by Django 4.1.3 on 2022-12-04 10:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0004_alter_customerorders_car_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerorders",
            name="currence_type",
        ),
        migrations.RemoveField(
            model_name="customerorders",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="customerorders",
            name="work_status",
        ),
        migrations.AddField(
            model_name="customerorderdetail",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Processed", "Processed"),
                    ("Not Processed", "Not Processed"),
                    ("Canceled", "Canceled"),
                ],
                default="Waiting",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="customerorders",
            name="chassis_no",
            field=models.CharField(
                blank=True,
                default="",
                help_text="car Chassis Nnumber ...",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerorders",
            name="car_name",
            field=models.CharField(
                help_text="Eg Toyota Land Cruiser ...", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="customerorders",
            name="plate_no",
            field=models.CharField(help_text="Eg  D200 TZ ...", max_length=255),
        ),
        migrations.AlterField(
            model_name="customerorders",
            name="problem_statement",
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text=" bio... "),
        ),
    ]
