# Generated by Django 4.1.3 on 2022-12-04 11:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0005_remove_customerorders_currence_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(help_text="enter vendor name ...", max_length=255),
                ),
                (
                    "vendor_email",
                    models.CharField(
                        blank=True,
                        help_text="enter vendor email ...",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "vendor_phone",
                    models.CharField(help_text="enter vendor phone..", max_length=255),
                ),
                (
                    "vendor_address",
                    models.CharField(
                        blank=True,
                        help_text="vendor address...",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Customers ",
            },
        ),
        migrations.CreateModel(
            name="VendorOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_name",
                    models.CharField(
                        help_text="Eg Toyota Land Cruiser ...", max_length=255
                    ),
                ),
                (
                    "plate_no",
                    models.CharField(help_text="Eg  D200 TZ ...", max_length=255),
                ),
                (
                    "model_no",
                    models.CharField(
                        blank=True, help_text="car model ...", max_length=255, null=True
                    ),
                ),
                (
                    "chassis_no",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="car Chassis Nnumber ...",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "problem_statement",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text=" bio... "
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                        default="Unpaid",
                        max_length=30,
                    ),
                ),
                ("arrival_date", models.DateTimeField(auto_now_add=True)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customerorder",
                        to="backoffice.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Outsource Order",
            },
        ),
        migrations.CreateModel(
            name="VendorOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Eg: PC, UNIt...",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=65),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("contractor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Processed", "Processed"),
                            ("Not Processed", "Not Processed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Waiting",
                        max_length=30,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_id",
                        to="backoffice.vendororders",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order Details",
            },
        ),
    ]
