# Generated by Django 4.1.3 on 2022-12-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0006_vendor_vendororders_vendororderdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorders",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Denied", "Denied"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="vendororders",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vorder",
                to="backoffice.vendor",
            ),
        ),
    ]
