# Generated by Django 4.1.3 on 2022-12-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0007_customerorders_work_status_alter_vendororders_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorders",
            name="payment_status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                default="Unpaid",
                max_length=30,
            ),
        ),
    ]
