# Generated by Django 4.1.3 on 2022-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0008_customerorders_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorders",
            name="job_card",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Job Card  Number ...",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerorders",
            name="chassis_no",
            field=models.CharField(
                blank=True,
                default="",
                help_text="car Chassis Number ...",
                max_length=255,
                null=True,
            ),
        ),
    ]
