# Generated by Django 4.1.3 on 2022-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0009_customerorders_job_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderdetail",
            name="parts_no",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customerorderdetail",
            name="unit",
            field=models.CharField(
                blank=True, help_text="Eg: PC, UNIT...", max_length=255, null=True
            ),
        ),
    ]
