# Generated by Django 4.1.3 on 2022-12-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0010_customerorderdetail_parts_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerorders",
            name="job_card",
        ),
        migrations.AddField(
            model_name="customerorders",
            name="number_of_km",
            field=models.IntegerField(
                blank=True,
                default="0",
                help_text="car km ...",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerorders",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Credit", "Credit")],
                default="Cash",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customerorderdetail",
            name="work_status",
            field=models.CharField(
                choices=[("Available", "Available"), ("Unavailable", "Unavailable")],
                default="Available",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customerorders",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Job completed not paid", "Job completed not paid"),
                    ("Job paid not completed", "Job paid not completed"),
                    ("Job paid completed", "Job paid completed"),
                ],
                default="Job completed not paid",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Staff", "Staff"),
                    ("Procurement", "Procurement"),
                    ("Accountant", "Accountant"),
                ],
                default="Staff",
                max_length=20,
            ),
        ),
    ]
