# Generated by Django 4.1.3 on 2022-12-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0011_remove_customerorders_job_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorderdetail",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Available", "Available"),
                    ("Unavailable", "Unavailable"),
                ],
                default="Waiting",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customerorders",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("New Job", "New Job"),
                    ("Job completed not paid", "Job completed not paid"),
                    ("Job paid not completed", "Job paid not completed"),
                    ("Job paid completed", "Job paid completed"),
                    ("Canceled", "Canceled"),
                ],
                default="New Job",
                max_length=30,
            ),
        ),
    ]
