# Generated by Django 4.1.3 on 2022-12-30 12:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0012_alter_customerorderdetail_work_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendororderdetail",
            name="contractor",
        ),
        migrations.RemoveField(
            model_name="vendororders",
            name="car_name",
        ),
        migrations.RemoveField(
            model_name="vendororders",
            name="chassis_no",
        ),
        migrations.RemoveField(
            model_name="vendororders",
            name="model_no",
        ),
        migrations.RemoveField(
            model_name="vendororders",
            name="plate_no",
        ),
        migrations.RemoveField(
            model_name="vendororders",
            name="problem_statement",
        ),
        migrations.AddField(
            model_name="vendororders",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="", help_text=" bio... "
            ),
        ),
        migrations.AddField(
            model_name="vendororders",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("Technical services", "Technical services"),
                    ("Purchases", "Purchases"),
                ],
                default="Technical services",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="vendororders",
            name="title",
            field=models.CharField(
                default="", help_text="Eg ufundi ...", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="vendororders",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="vendororderdetail",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("On Progress", "On Progress"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                ],
                default="Waiting",
                max_length=30,
            ),
        ),
    ]
