# Generated by Django 4.1.3 on 2022-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0013_remove_vendororderdetail_contractor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendororders",
            old_name="departure_date",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="vendororders",
            old_name="arrival_date",
            new_name="start_date",
        ),
        migrations.AlterField(
            model_name="customerorders",
            name="number_of_km",
            field=models.CharField(
                blank=True,
                default="0",
                help_text="car km ...",
                max_length=255,
                null=True,
            ),
        ),
    ]
