# Generated by Django 4.1.3 on 2022-12-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0014_rename_departure_date_vendororders_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderdetail",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Not Delivered", "Not Delivered"),
                ],
                default="Not Delivered",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customerorderdetail",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Available", "Available"),
                    ("Unavailable", "Unavailable"),
                    ("Dispatched", "Dispatched"),
                ],
                default="Waiting",
                max_length=30,
            ),
        ),
    ]
