# Generated by Django 4.1.3 on 2023-01-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0015_customerorderdetail_item_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendororders",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Credit", "Credit")],
                default="Cash",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customerorderdetail",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Not Delivered", "Not Delivered"),
                    ("Received", "Received"),
                ],
                default="Not Delivered",
                max_length=30,
            ),
        ),
    ]
