# Generated by Django 4.1.3 on 2023-02-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_department_alter_requisitiondetails_supplier'),
        ('backoffice', '0017_vendorordercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='department',
            field=models.ManyToManyField(default='1', to='workshop.department'),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='service_by',
            field=models.CharField(default='', help_text='Staff name', max_length=255),
        ),
    ]
